#pragma once
#include "CoreMinimal.h"
#include "EScePadTriggerEffectMode.generated.h"

UENUM(BlueprintType)
enum class EScePadTriggerEffectMode : uint8 {
    SCE_PAD_TRIGGER_EFFECT_MODE_OFF,
    SCE_PAD_TRIGGER_EFFECT_MODE_FEEDBACK,
    SCE_PAD_TRIGGER_EFFECT_MODE_WEAPON,
    SCE_PAD_TRIGGER_EFFECT_MODE_VIBRATION,
    SCE_PAD_TRIGGER_EFFECT_MODE_MULTIPLE_POSITION_FEEDBACK,
    SCE_PAD_TRIGGER_EFFECT_MODE_SLOPE_FEEDBACK,
    SCE_PAD_TRIGGER_EFFECT_MODE_MULTIPLE_POSITION_VIBRATION,
};

