#include "SteamCoreProInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs.h"

USteamCoreProInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs::USteamCoreProInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs() {
}

USteamCoreProInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs* USteamCoreProInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs::RequestEligiblePromoItemDefinitionsIDsAsync(UObject* WorldContextObject, FSteamID SteamID, float Timeout) {
    return NULL;
}

void USteamCoreProInventoryAsyncActionRequestEligiblePromoItemDefinitionsIDs::HandleCallback(const FSteamInventoryEligiblePromoItemDefIDs& Data, bool bWasSuccessful) {
}


